locale: "en-US"
title: "Blog Title"
title_separator: "|"
subtitle: "Information security blog"
name: "Michael Rose"
email:
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://cybercyio.github.io"
baseurl: # the subpath of your site, e.g. "/blog"
repository: # GitHub username/repo-name e.g. "cybercyio/cybercyio.github.io"
teaser: "/assets/images/network-3443540_1920.jpg"
logo: "/assets/images/icon-5381273_1920.jpg"
masthead_title: # "An Information security blog"
breadcrumbs: true # true, false (default)
breadcrumb_separator  : "/"
words_per_minute: 200
twitter_username: cybercyio
github_username: cybercyio
minimal_mistakes_skin: air # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true
search_full_content: true # true, false (default)
search_provider: lunr # lunr (default), algolia, google
toc: true
toc_label: "Content: "
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "<!--more-->"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
permalink: /:title
paginate: 4 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
include:
  - _pages
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
author:
  name   : "Rocky Balboa"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Life-long pentester, fresh threat hunter"
  #location : "Somewhere, USA"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/cybercyio"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cybercyio"
footer:
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      show_date: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
